export const Users = [
    {
        id:1,
        profilePicture: "/img/person4.jpg",
        username: "Anna Paruryan",
    },
    {
        id:2,
        profilePicture: "/img/person1.jpg",
        username: "Jane Tomline",
    },
    {
        id:3,
        profilePicture: "/img/person2.jpg",
        username: "Alex Bolduin",
    },
    {
        id:4,
        profilePicture: "/img/person3.jpg",
        username: "Tomas Scot",
    },
    {
        id:5,
        profilePicture: "/img/person5.jpg",
        username: "Hellen Bocman",
    },
    {
        id:6,
        profilePicture: "/img/person6.jpg",
        username: " Ann Shirley  ",
    },
    {
        id:7,
        profilePicture: "/img/person2.jpg",
        username: "Tonny Bennett",
    },
    {
        id:8,
        profilePicture: "/img/person5.jpg",
        username: "Angele Thomas",
    },
    {
        id:9,
        profilePicture: "/img/person4.jpg",
        username: "Gary Poter",
    },
    {
        id:10,
        profilePicture: "/img/person6.jpg",
        username: "Harry Metyu",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "/img/post1.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "/img/post2.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "/img/post3.jpg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "/img/post4.jpg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "/img/post5.jpg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "/img/post6.jpg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Never regret anything that made you smile.",
        photo: "/img/post7.jpg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "/img/post1.jpg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "Change the world by being yourself.",
        photo: "/img/post2.jpg",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "/img/post3.jpg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
];